spring:
  application:
    name: ffm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://192.168.1.248:3306/ffm
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: never
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema-mysql.sql
#  sql:
#    init:
#      #mode: never
#      #schema-locations: classpath:schema-h2.sql
#      mode: always
#      data-locations: classpath:clear-batch-tables.sql

#logging:
#  level:
#    org:
#      hibernate: INFO
#      SQL: DEBUG
#      cache: DEBUG
#      stat: DEBUG
#      springframework:
#        batch: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

ffm:
  batch:
    excel-giocatori:
      skip-rows: 2
      sheet-name: 'Tutti'
    csv-rose:
      skip-rows: 1
    excel-risultati-competizione:
      skip-rows: 3
      sheet-name: 'Calendario'
      giornata: 9999
