spring:
  application:
    name: ffm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://192.168.1.248:3306/ffm
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: never
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema-mysql.sql
#  sql:
#    init:
#      #mode: never
#      #schema-locations: classpath:schema-h2.sql
#      mode: always
#      data-locations: classpath:clear-batch-tables.sql

#logging:
#  level:
#    org:
#      hibernate: INFO
#      SQL: DEBUG
#      cache: DEBUG
#      stat: DEBUG
#      springframework:
#        batch: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

ffm:
  batch:
    excel-giocatori:
      skip-rows: 2
      sheet-name: 'Tutti'
    csv-rose:
      skip-rows: 1
    excel-risultati-competizione:
      skip-rows: 3
      sheet-name: 'Calendario'
      giornata: 9999
  web:
    api-fantaleghe:
      domain-url: https://apileague.fantacalcio.it
      headers:
        host: 'apileague.fantacalcio.it'
        app-key: '0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a'
        accept: 'application/json'
        accept-encoding: 'gzip, deflate, br'
        content-type: 'application/json'
        user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
      login-endpoint: "${ffm.web.api-fantaleghe.domain-url}/onboarding/v1/login"
      teams-endpoint: "${ffm.web.api-fantaleghe.domain-url}/onboarding/v1/league/teams"
      mercati-conclusi-endpoint: "${ffm.web.api-fantaleghe.domain-url}/market/v1/expired"
      # da aggiungere dinamicamente all'url in base a categoria esempio per A: /A?
      mercati-svincoli: "${ffm.web.api-fantaleghe.domain-url}/market/v1/hiddenrelease/releases/closed"
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato esempio: /A/MK_20250117134307
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato?lastId=codiceLastIdPaginaPrecedente esempio: ?lastId=MTcxNDU4NS1BLU1LXzIwMjUwMTE3MTM0MzA3JGNsb3NlZC02ODIyMzk2LTIwMjUwMjAxMTEwMC01NDg2JGNsb3NlZC0yMDI1MDIwMTExMDA
      mercati-acquisti: "${ffm.web.api-fantaleghe.domain-url}/market/v1/smartauction/purchases/closed"
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato esempio: /A/MK_20250117134307
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato?lastId=codiceLastIdPaginaPrecedente esempio: ?lastId=MTcxNDU4NS1BLU1LXzIwMjUwMTE3MTM0MzA3JGNsb3NlZC02ODIyMzk2LTIwMjUwMjAxMTEwMC01NDg2JGNsb3NlZC0yMDI1MDIwMTExMDA
      mercati-svincoli-acquisti: "${ffm.web.api-fantaleghe.domain-url}/market/v1/smartauction/purchases/freeagency"
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato esempio: /A/MK_20250117134307
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato?lastId=codiceLastIdPaginaPrecedente esempio: ?lastId=MTcxNDU4NS1BLU1LXzIwMjUwMTE3MTM0MzA3JGNsb3NlZC02ODIyMzk2LTIwMjUwMjAxMTEwMC01NDg2JGNsb3NlZC0yMDI1MDIwMTExMDA
      mercati-buste: "${ffm.web.api-fantaleghe.domain-url}/market/v1/sealedbid/purchases/closed"
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato esempio: /A/MK_20250117134307
      # da aggiungere dinamicamente all'url in base a categoria/codice mercato?lastId=codiceLastIdPaginaPrecedente esempio: ?lastId=MTcxNDU4NS1BLU1LXzIwMjUwMTE3MTM0MzA3JGNsb3NlZC02ODIyMzk2LTIwMjUwMjAxMTEwMC01NDg2JGNsb3NlZC0yMDI1MDIwMTExMDA

