spring:
  application:
    name: ffm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://192.168.1.248:3306/ffm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate: INFO
      SQL: DEBUG
      cache: DEBUG
      stat: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html